### PR TITLE
Fix the issue in question

### LINKED ISSUE #132: Use updateWatchStatus in AddToListButton
Right now when you click the save button when adding a movie, the regular addToList function is used even if the movie already exists in some list. It's probably more efficient to use the update function instead.

### PR DESCRIPTION
**Pull request by pajlilja**
Fixes #132

### CODE REVIEW

File: src/containers/AddToListBtn.js [hunk 1]
```diff
@@ -68,12 +68,18 @@ class AddToListBtn extends Component {
 
     const { currentMovie } = this.props;
     const movie = normalizeMovie(currentMovie);
-    try {
-      await addToList(movie, selectedList);
-      successToast(`Added ${movie.title} to ${parseName(selectedList)}`);
+    if (this.state.statusOfCurrentMovie) {
```
Comment (willwull) [inline src/containers/AddToListBtn.js]: The if-statement should maybe be in the `try` block, because if `updateWatchStatus` fails, there should be an error message.
